spring:
  profiles:
    active:
    - development
  datasource:
    url: jdbc:h2:mem:testdb
  #jpa:
   # hibernate:
     # ddl-auto: create
  #datasource:
   # initialization-mode: always
   # platform: postgres
   # url: jdbc:postgresql://localhost:5432/testdb
    #username: postgres
    #password: 1234
logging:
  level:
     org.springframework: info